In [1]:
import json

In [2]:
import pandas as pd

In [2]:
with open("./data/com_kbstar_kbbank.json", encoding = "utf-8") as file:
    raw_data2 = file.read()
    bank_data = json.loads(raw_data2)

In [3]:
len(bank_data)

2223

In [4]:
bank_data[0]

{'사용자': '박성진 (홀리진)',
 '별점': '4',
 '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
 '날짜': '2025년 3월 2일',
 '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}

In [5]:
for key in bank_data[0]:
    print(key)

사용자
별점
리뷰
날짜
개발자 응답

In [28]:
#import time
result1 = {}
for key in bank_data[0]:
    temp = []
    for item in bank_data:
#        time.sleep(0.01)
        temp.append(item[key])
#        print(f"{key} : ", temp)
        result1[key] = temp
result1

{'사용자': ['박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '뇌절연구소',
  'YJ S',
  '__',
  'huihwan kim',
  '천벌의토템',
  '최은경',
  'SU영감',
  '박예솔',
  '미카엘',
  'Youngmi Son',
  'Y',
  'M곰이 (웅이)',
  '강재인',
  'sa ro',
  '수혁',
  'IW P.',
  '최경국',
  '안준서',
  'Es k',
  '안유진',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  ...],
 '별점': ['4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '2',
  '4',
  '1',
  '3',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '4',
  '2',
  '1',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  ...],
 '리뷰': ['리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',

In [29]:
len(result1["사용자"])

2223

In [2]:
import pandas as pd

In [30]:
df = pd.DataFrame(result1)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

* setdefault() 이용

In [10]:
result2 = {}
for item in bank_data:
    for key, value in item.items():
        result2.setdefault(key, []).append(value)
result2

{'사용자': ['박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '뇌절연구소',
  'YJ S',
  '__',
  'huihwan kim',
  '천벌의토템',
  '최은경',
  'SU영감',
  '박예솔',
  '미카엘',
  'Youngmi Son',
  'Y',
  'M곰이 (웅이)',
  '강재인',
  'sa ro',
  '수혁',
  'IW P.',
  '최경국',
  '안준서',
  'Es k',
  '안유진',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  ...],
 '별점': ['4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '2',
  '4',
  '1',
  '3',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '4',
  '2',
  '1',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  ...],
 '리뷰': ['리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',

In [18]:
len(result2["사용자"])

2223

In [12]:
df = pd.DataFrame(result2)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

* defaultdict 이용

In [13]:
from collections import defaultdict

In [14]:
dic_result = defaultdict(list)
dic_result

defaultdict(list, {})

In [15]:
for item in bank_data:
    for key, value in item.items():
        dic_result[key].append(value)
result3 = dict(dic_result)
result3

{'사용자': ['박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '뇌절연구소',
  'YJ S',
  '__',
  'huihwan kim',
  '천벌의토템',
  '최은경',
  'SU영감',
  '박예솔',
  '미카엘',
  'Youngmi Son',
  'Y',
  'M곰이 (웅이)',
  '강재인',
  'sa ro',
  '수혁',
  'IW P.',
  '최경국',
  '안준서',
  'Es k',
  '안유진',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  ...],
 '별점': ['4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '2',
  '4',
  '1',
  '3',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '4',
  '2',
  '1',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  ...],
 '리뷰': ['리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',

In [17]:
len(result3["사용자"])

2223

In [19]:
df = pd.DataFrame(result3)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

In [27]:
df["리뷰"][2019]

'앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..'

* 강사님 코드

In [5]:
result = {}
for item in bank_data:
    for key, value in item.items():
        if key == "별점":
            value = int(value)
        elif key == "리뷰":
            value = value.replace("?", " ").replace(".", "").replace("ㅋ", "")
        elif key == "개발자 응답":
            if value != None:
                value = value.replace("?", " ").replace(".", "").replace("ㅋ", "")
#        value = value.replace("?", " ").replace(".", "").replace("ㅋ", "") if value != None else "None" ->위의 두 줄 합쳐서 이렇게도 씀
        result.setdefault(key, []).append(value)
df = pd.DataFrame(result)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다 현금이나 실물 카...,2025년 3월 2일,"고객님, 안녕하세요 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다 가...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹은...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임 그리고 메뉴이동도 불편함 뒤로가기를...,2025년 1월 14일,안녕하세요 고객님 KB스타뱅킹 이용에 불편을 드려 죄송합니다 고객님의 의견을 증명서...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다 하나하나 집중해서 잘했는데 갑...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹은...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,"고객님 안녕하세요 KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다 사용자암호, ..."
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹은...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만네트워크문제였었으면 타...,2024년 12월 26일,안녕하세요 KB스타뱅킹 이용에 불편을 드려 죄송합니다 앱 구동이 원활하지 않을 경우...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹은...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹은...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다 와이파이가 매우 잘 작동하는 상황에서도...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다 앱 이용 시..."

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2223 entries, 0 to 2222
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용자     2223 non-null   object
 1   별점      2223 non-null   int64
 2   리뷰      2223 non-null   object
 3   날짜      2223 non-null   object
 4   개발자 응답  1912 non-null   object
dtypes: int64(1), object(4)
memory usage: 87.0+ KB

In [7]:
df.to_csv("./data/국민은행_앱리뷰.csv", index = False, encoding = "utf-8-sig")

# 전국 치킨집 리스트 데이터 정리하기

In [3]:
with open("./data/전국치킨집리스트.json") as file:
    raw_data = file.read()
    data = json.loads(raw_data)

In [4]:
len(data) # 37 페이지, 페이지당 1,000개의 가게 정보

37

In [5]:
data[0]

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202206',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': '10027626',
    'bizesNm': '장모님치킨가창점',
    'brchNm': '가창점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '27',
    'ctprvnNm': '대구광역시',
    'signguCd': '27710',
    'signguNm': '달성군',
    'adongCd': '2771031000',
    'adongNm': '가창면',
    'ldongCd': '2771031024',
    'ldongNm': '가창면',
    'lnoCd': '2771031024101200001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 120,
    'lnoSlno': 1,
    'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1',
    'rdnmCd': '277103148001',
    'rdnm': '대구광역시 달성군 가창면 가창동로',
    'bldMnno': 6,
    'bldSlno': '',
    'bldMngNo': '2771031024101200004036858',
    'bldNm': '',
    'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6',
    'oldZipcd': '711861',
    'newZipcd': '42938',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.644458591419,
    'lat': 35.7826625402814},
   {'bizesId': '10098244',
    'bizesNm': '짱구피자치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41250',
    'signguNm': '동두천시',
    'adongCd': '4125056500',
    'adongNm': '불현동',
    'ldongCd': '4125010300',
    'ldongNm': '생연동',
    'lnoCd': '4125010300102680011',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 268,
    'lnoSlno': 11,
    'lnoAdr': '경기도 동두천시 생연동 268-11',
    'rdnmCd': '412503189006',
    'rdnm': '경기도 동두천시 못골로',
    'bldMnno': 30,
    'bldSlno': '',
    'bldMngNo': '4125010300102680011008557',
    'bldNm': '',
    'rdnmAdr': '경기도 동두천시 못골로 30',
    'oldZipcd': '483030',
    'newZipcd': '11320',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.06590346074,
    'lat': 37.9012616518346},
   {'bizesId': '10099459',
    'bizesNm': '쭈노치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41570',
    'signguNm': '김포시',
    'adongCd': '4157025300',
    'adongNm': '고촌읍',
    'ldongCd': '4157025324',
    'ldongNm': '고촌읍',
    'lnoCd': '4157025324105380008',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 538,
    'lnoSlno': 8,
    'lnoAdr': '경기도 김포시 고촌읍 신곡리 538-8',
    'rdnmCd': '415704427512',
    'rdnm': '경기도 김포시 고촌읍 장차로13번길',
    'bldMnno': 18,
    'bldSlno': '',
    'bldMngNo': '4157025324105380008019970',
    'bldNm': '',
    'rdnmAdr': '경기도 김포시 고촌읍 장차로13번길 18',
    'oldZipcd': '415811',
    'newZipcd': '10126',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.769859060814,
    'lat': 37.6037515030602},
   {'bizesId': '10136167',
    'bizesNm': '치킨뱅이',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42130',
    'signguNm': '원주시',
    'adongCd': '4213059000',
    'adongNm': '단계동',
    'ldongCd': '4213011000',
    'ldongNm': '단계동',
    'lnoCd': '4213011000108300006',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 830,
    'lnoSlno': 6,
    'lnoAdr': '강원도 원주시 단계동 830-6',
    'rdnmCd': '421304457083',
    'rdnm': '강원도 원주시 금불3길',
    'bldMnno': 5,
    'bldSlno': '',
    'bldMngNo': '4213011000108300006022278',
    'bldNm': '',
    'rdnmAdr': '강원도 원주시 금불3길 5',
    'oldZipcd': '220938',
    'newZipcd': '26423',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.932025388709,
    'lat': 37.3483579547022},
   {'bizesId': '10136346',
    'bizesNm': '치킨월드율량점',
    'brchNm': '율량점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '43',
    'ctprvnNm': '충청북도',
    'signguCd': '43114',
    'signguNm': '청주시 청원구',
    'adongCd': '4311454000',
    'adongNm': '율량.사천동',
    'ldongCd': '4311410300',
    'ldongNm': '율량동',
    'lnoCd': '4311410300108060000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 806,
    'lnoSlno': '',
    'lnoAdr': '충청북도 청주시 청원구 율량동 806',
    'rdnmCd': '431144508043',
    'rdnm': '충청북도 청주시 청원구 공항로138번길',
    'bldMnno': 53,
    'bldSlno': '',
    'bldMngNo': '4311111500108060000045239',
    'bldNm': '',
    'rdnmAdr': '충청북도 청주시 청원구 공항로138번길 53',
    'oldZipcd': '363818',
    'newZipcd': '28328',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.487585541514,
    'lat': 36.6698161542425},
   {'bizesId': '10150151',
    'bizesNm': 'KFC',
    'brchNm': '수원이마트점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41113',
    'signguNm': '수원시 권선구',
    'adongCd': '4111368000',
    'adongNm': '권선2동',
    'ldongCd': '4111313700',
    'ldongNm': '권선동',
    'lnoCd': '4111313700111890000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1189,
    'lnoSlno': '',
    'lnoAdr': '경기도 수원시 권선구 권선동 1189',
    'rdnmCd': '411132012008',
    'rdnm': '경기도 수원시 권선구 경수대로',
    'bldMnno': 270,
    'bldSlno': '',
    'bldMngNo': '4111313700111890000027851',
    'bldNm': '할인점동',
    'rdnmAdr': '경기도 수원시 권선구 경수대로 270',
    'oldZipcd': '441713',
    'newZipcd': '16585',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.020087664145,
    'lat': 37.2501017782401},
   {'bizesId': '10186527',
    'bizesNm': '토마토두마리치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11440',
    'signguNm': '마포구',
    'adongCd': '1144063000',
    'adongNm': '신수동',
    'ldongCd': '1144011300',
    'ldongNm': '구수동',
    'lnoCd': '1144011300100700001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 70,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 마포구 구수동 70-1',
    'rdnmCd': '114403113023',
    'rdnm': '서울특별시 마포구 토정로',
    'bldMnno': 195,
    'bldSlno': 1,
    'bldMngNo': '1144011300100700001008546',
    'bldNm': '정우빌딩',
    'rdnmAdr': '서울특별시 마포구 토정로 195-1',
    'oldZipcd': '121130',
    'newZipcd': '04087',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.932820696234,
    'lat': 37.545508849345},
   {'bizesId': '10208331',
    'bizesNm': '페리카나치킨연수우성체인점',
    'brchNm': '연수우성체인점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '28',
    'ctprvnNm': '인천광역시',
    'signguCd': '28185',
    'signguNm': '연수구',
    'adongCd': '2818576200',
    'adongNm': '연수2동',
    'ldongCd': '2818510300',
    'ldongNm': '연수동',
    'lnoCd': '2818510300106340000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 634,
    'lnoSlno': '',
    'lnoAdr': '인천광역시 연수구 연수동 634',
    'rdnmCd': '281853152021',
    'rdnm': '인천광역시 연수구 원인재로',
    'bldMnno': 180,
    'bldSlno': '',
    'bldMngNo': '2818510300106340000007257',
    'bldNm': '연수우성2차아파트',
    'rdnmAdr': '인천광역시 연수구 원인재로 180',
    'oldZipcd': '406765',
    'newZipcd': '21931',
    'dongNo': '',
    'flrNo': '2',
    'hoNo': '',
    'lon': 126.683928104747,
    'lat': 37.4122665635834},
   {'bizesId': '10208355',
    'bizesNm': '페리카나치킨벽산분점',
    'brchNm': '벽산분점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42130',
    'signguNm': '원주시',
    'adongCd': '4213059000',
    'adongNm': '단계동',
    'ldongCd': '4213011000',
    'ldongNm': '단계동',
    'lnoCd': '4213011000108130012',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 813,
    'lnoSlno': 12,
    'lnoAdr': '강원도 원주시 단계동 813-12',
    'rdnmCd': '421304457083',
    'rdnm': '강원도 원주시 금불3길',
    'bldMnno': 34,
    'bldSlno': '',
    'bldMngNo': '4213011000108130012022273',
    'bldNm': '',
    'rdnmAdr': '강원도 원주시 금불3길 34',
    'oldZipcd': '220938',
    'newZipcd': '26423',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.93187697793,
    'lat': 37.3502141596654},
   {'bizesId': '10208360',
    'bizesNm': '페리카나치킨',
    'brchNm': '송천점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '45',
    'ctprvnNm': '전라북도',
    'signguCd': '45113',
    'signguNm': '전주시 덕진구',
    'adongCd': '4511364100',
    'adongNm': '송천1동',
    'ldongCd': '4511312100',
    'ldongNm': '송천동1가',
    'lnoCd': '4511312100101070143',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 107,
    'lnoSlno': 143,
    'lnoAdr': '전라북도 전주시 덕진구 송천동1가 107-143',
    'rdnmCd': '451134601338',
    'rdnm': '전라북도 전주시 덕진구 오송1길',
    'bldMnno': 15,
    'bldSlno': '',
    'bldMngNo': '4511312100101070143016691',
    'bldNm': '',
    'rdnmAdr': '전라북도 전주시 덕진구 오송1길 15',
    'oldZipcd': '561816',
    'newZipcd': '54823',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.128483752173,
    'lat': 35.8631606134181},
   {'bizesId': '10231561',
    'bizesNm': '피자앤닭컴',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41281',
    'signguNm': '고양시 덕양구',
    'adongCd': '4128160000',
    'adongNm': '관산동',
    'ldongCd': '4128111900',
    'ldongNm': '내유동',
    'lnoCd': '4128111900109030014',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 903,
    'lnoSlno': 14,
    'lnoAdr': '경기도 고양시 덕양구 내유동 903-14',
    'rdnmCd': '412814379207',
    'rdnm': '경기도 고양시 덕양구 통일로1267번길',
    'bldMnno': 12,
    'bldSlno': '',
    'bldMngNo': '4128111900109030014007802',
    'bldNm': '',
    'rdnmAdr': '경기도 고양시 덕양구 통일로1267번길 12',
    'oldZipcd': '412520',
    'newZipcd': '10262',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.842370394144,
    'lat': 37.7250861314577},
   {'bizesId': '10242205',
    'bizesNm': '하림치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48270',
    'signguNm': '밀양시',
    'adongCd': '4827034000',
    'adongNm': '산내면',
    'ldongCd': '4827034028',
    'ldongNm': '산내면',
    'lnoCd': '4827034028111160004',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1116,
    'lnoSlno': 4,
    'lnoAdr': '경상남도 밀양시 산내면 남명리 1116-4',
    'rdnmCd': '482703336029',
    'rdnm': '경상남도 밀양시 산내면 산내로',
    'bldMnno': 1134,
    'bldSlno': '',
    'bldMngNo': '4827034028111160004000237',
    'bldNm': '',
    'rdnmAdr': '경상남도 밀양시 산내면 산내로 1134',
    'oldZipcd': '627832',
    'newZipcd': '50415',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.952863807002,
    'lat': 35.5878569482513},
   {'bizesId': '10274423',
    'bizesNm': '핫썬치킨옥동점',
    'brchNm': '옥동점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '47',
    'ctprvnNm': '경상북도',
    'signguCd': '47170',
    'signguNm': '안동시',
    'adongCd': '4717065000',
    'adongNm': '옥동',
    'ldongCd': '4717013300',
    'ldongNm': '옥동',
    'lnoCd': '4717013300107870006',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 787,
    'lnoSlno': 6,
    'lnoAdr': '경상북도 안동시 옥동 787-6',
    'rdnmCd': '471704721489',
    'rdnm': '경상북도 안동시 복주1길',
    'bldMnno': 92,
    'bldSlno': '',
    'bldMngNo': '4717013300107870006027092',
    'bldNm': '',
    'rdnmAdr': '경상북도 안동시 복주1길 92',
    'oldZipcd': '760310',
    'newZipcd': '36661',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.701658516225,
    'lat': 36.5633746443297},
   {'bizesId': '10398264',
    'bizesNm': 'BHC치킨',
    'brchNm': '강북점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42110',
    'signguNm': '춘천시',
    'adongCd': '4211070500',
    'adongNm': '신사우동',
    'ldongCd': '4211011900',
    'ldongNm': '사농동',
    'lnoCd': '4211011900100320003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 32,
    'lnoSlno': 3,
    'lnoAdr': '강원도 춘천시 사농동 32-3',
    'rdnmCd': '421104454187',
    'rdnm': '강원도 춘천시 마장길',
    'bldMnno': 62,
    'bldSlno': '',
    'bldMngNo': '4211011900100320003012141',
    'bldNm': '',
    'rdnmAdr': '강원도 춘천시 마장길 62',
    'oldZipcd': '200140',
    'newZipcd': '24221',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.730540190041,
    'lat': 37.9093809548376},
   {'bizesId': '10407416',
    'bizesNm': '치킨아이',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '29',
    'ctprvnNm': '광주광역시',
    'signguCd': '29170',
    'signguNm': '북구',
    'adongCd': '2917066900',
    'adongNm': '일곡동',
    'ldongCd': '2917012700',
    'ldongNm': '일곡동',
    'lnoCd': '2917012700108160003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 816,
    'lnoSlno': 3,
    'lnoAdr': '광주광역시 북구 일곡동 816-3',
    'rdnmCd': '291704286581',
    'rdnm': '광주광역시 북구 우치로537번길',
    'bldMnno': 10,
    'bldSlno': 1,
    'bldMngNo': '2917012700108160003015135',
    'bldNm': '동아아파트',
    'rdnmAdr': '광주광역시 북구 우치로537번길 10-1',
    'oldZipcd': '500795',
    'newZipcd': '61031',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.899570717972,
    'lat': 35.2126556214737},
   {'bizesId': '10423599',
    'bizesNm': '더화덕',
    'brchNm': '중동점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48121',
    'signguNm': '창원시 의창구',
    'adongCd': '4812151000',
    'adongNm': '의창동',
    'ldongCd': '4812110300',
    'ldongNm': '서상동',
    'lnoCd': '4812110300106680010',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 668,
    'lnoSlno': 10,
    'lnoAdr': '경상남도 창원시 의창구 서상동 668-10',
    'rdnmCd': '481214781529',
    'rdnm': '경상남도 창원시 의창구 의창대로254번길',
    'bldMnno': 19,
    'bldSlno': '',
    'bldMngNo': '4812110200103710009067614',
    'bldNm': '',
    'rdnmAdr': '경상남도 창원시 의창구 의창대로254번길 19',
    'oldZipcd': '641500',
    'newZipcd': '51370',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.625322165672,
    'lat': 35.2595259139192},
   {'bizesId': '10446382',
    'bizesNm': '월드양념통닭',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26380',
    'signguNm': '사하구',
    'adongCd': '2638058000',
    'adongNm': '장림1동',
    'ldongCd': '2638010500',
    'ldongNm': '장림동',
    'lnoCd': '2638010500106410130',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 641,
    'lnoSlno': 130,
    'lnoAdr': '부산광역시 사하구 장림동 641-130',
    'rdnmCd': '263804202433',
    'rdnm': '부산광역시 사하구 장림시장3길',
    'bldMnno': 80,
    'bldSlno': '',
    'bldMngNo': '2638010500106410130018701',
    'bldNm': '',
    'rdnmAdr': '부산광역시 사하구 장림시장3길 80',
    'oldZipcd': '604040',
    'newZipcd': '49476',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.967851385835,
    'lat': 35.0806599306185},
   {'bizesId': '10482089',
    'bizesNm': 'BBQ치킨',
    'brchNm': '진접센트레빌점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41360',
    'signguNm': '남양주시',
    'adongCd': '4136025300',
    'adongNm': '진접읍',
    'ldongCd': '4136025325',
    'ldongNm': '진접읍',
    'lnoCd': '4136025325107640000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 764,
    'lnoSlno': '',
    'lnoAdr': '경기도 남양주시 진접읍 부평리 764',
    'rdnmCd': '413603197029',
    'rdnm': '경기도 남양주시 진접읍 부평로',
    'bldMnno': 32,
    'bldSlno': '',
    'bldMngNo': '4136025325107640000000016',
    'bldNm': '진접센트레빌시티1단지상가',
    'rdnmAdr': '경기도 남양주시 진접읍 부평로 32',
    'oldZipcd': '472856',
    'newZipcd': '12022',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.200193095712,
    'lat': 37.7401667347414},
   {'bizesId': '10623611',
    'bizesNm': '치킨마루',
    'brchNm': '현대시장점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11620',
    'signguNm': '관악구',
    'adongCd': '1162060500',
    'adongNm': '은천동',
    'ldongCd': '1162010100',
    'ldongNm': '봉천동',
    'lnoCd': '1162010100117080000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1708,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 관악구 봉천동 1708',
    'rdnmCd': '116203005083',
    'rdnm': '서울특별시 관악구 봉천로',
    'bldMnno': 387,
    'bldSlno': '',
    'bldMngNo': '1162010100117080000040043',
    'bldNm': '두산아파트',
    'rdnmAdr': '서울특별시 관악구 봉천로 387',
    'oldZipcd': '151782',
    'newZipcd': '08750',
    'dongNo': '2',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.9427601496,
    'lat': 37.484309081691},
   {'bizesId': '10663586',
    'bizesNm': '교촌치킨',
    'brchNm': '신개금점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26230',
    'signguNm': '부산진구',
    'adongCd': '2623074000',

In [6]:
len(data)

37

In [7]:
print(type(data[0]))

<class 'dict'>

In [8]:
len(data[0])

2

In [9]:
len(data[0]["body"]["items"][0])

39

In [10]:
data[0]["body"]["items"][0].items()

dict_items([('bizesId', '10027626'), ('bizesNm', '장모님치킨가창점'), ('brchNm', '가창점'), ('indsLclsCd', 'Q'), ('indsLclsNm', '음식'), ('indsMclsCd', 'Q05'), ('indsMclsNm', '닭/오리요리'), ('indsSclsCd', 'Q05A08'), ('indsSclsNm', '후라이드/양념치킨'), ('ksicCd', 'I56193'), ('ksicNm', '치킨 전문점'), ('ctprvnCd', '27'), ('ctprvnNm', '대구광역시'), ('signguCd', '27710'), ('signguNm', '달성군'), ('adongCd', '2771031000'), ('adongNm', '가창면'), ('ldongCd', '2771031024'), ('ldongNm', '가창면'), ('lnoCd', '2771031024101200001'), ('plotSctCd', '1'), ('plotSctNm', '대지'), ('lnoMnno', 120), ('lnoSlno', 1), ('lnoAdr', '대구광역시 달성군 가창면 냉천리 120-1'), ('rdnmCd', '277103148001'), ('rdnm', '대구광역시 달성군 가창면 가창동로'), ('bldMnno', 6), ('bldSlno', ''), ('bldMngNo', '2771031024101200004036858'), ('bldNm', ''), ('rdnmAdr', '대구광역시 달성군 가창면 가창동로 6'), ('oldZipcd', '711861'), ('newZipcd', '42938'), ('dongNo', ''), ('flrNo', '1'), ('hoNo', ''), ('lon', 128.644458591419), ('lat', 35.7826625402814)])

In [11]:
result2 = {}
for key, value in data[0]["body"]["items"][0].items():
    result2.setdefault(key, []).append(value)
df2 = pd.DataFrame(result2)
df2

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663

In [12]:
result2 = {}
for page in data:
    for shop in page ["body"]["items"]:
        for key, value in shop.items():
            result2.setdefault(key, []).append(value)
df2 = pd.DataFrame(result2)
df2

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36059,9829515,아리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010200106740003008662,,경기도 동두천시 거북마루로 6,483020,11348,,1,,127.046713,37.895702
36060,9851302,애니치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4785031036104090002008916,,경상북도 칠곡군 지천면 신동로 147,718821,39864,,,,128.488717,35.956631
36061,9867543,에디슨치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1135010600103590001010681,중계5단지주공아파트,서울특별시 노원구 중계로 230,139781,01713,,1,,127.075031,37.651004
36062,9918905,오븐에꾸운닭장유점,장유점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4825031027103150002091993,재영프라자,경상남도 김해시 삼문로 26,621280,51004,,1,,128.803565,35.192491
36063,9967953,웰빙치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011100101360002016167,,강원도 원주시 상지대길 43,220954,26342,,1,,127.937290,37.369591

In [13]:
len(data)

37

In [14]:
len(data[0]["body"]["items"])

1000

In [15]:
data[0]["body"]["items"][0].items()

dict_items([('bizesId', '10027626'), ('bizesNm', '장모님치킨가창점'), ('brchNm', '가창점'), ('indsLclsCd', 'Q'), ('indsLclsNm', '음식'), ('indsMclsCd', 'Q05'), ('indsMclsNm', '닭/오리요리'), ('indsSclsCd', 'Q05A08'), ('indsSclsNm', '후라이드/양념치킨'), ('ksicCd', 'I56193'), ('ksicNm', '치킨 전문점'), ('ctprvnCd', '27'), ('ctprvnNm', '대구광역시'), ('signguCd', '27710'), ('signguNm', '달성군'), ('adongCd', '2771031000'), ('adongNm', '가창면'), ('ldongCd', '2771031024'), ('ldongNm', '가창면'), ('lnoCd', '2771031024101200001'), ('plotSctCd', '1'), ('plotSctNm', '대지'), ('lnoMnno', 120), ('lnoSlno', 1), ('lnoAdr', '대구광역시 달성군 가창면 냉천리 120-1'), ('rdnmCd', '277103148001'), ('rdnm', '대구광역시 달성군 가창면 가창동로'), ('bldMnno', 6), ('bldSlno', ''), ('bldMngNo', '2771031024101200004036858'), ('bldNm', ''), ('rdnmAdr', '대구광역시 달성군 가창면 가창동로 6'), ('oldZipcd', '711861'), ('newZipcd', '42938'), ('dongNo', ''), ('flrNo', '1'), ('hoNo', ''), ('lon', 128.644458591419), ('lat', 35.7826625402814)])

In [16]:
for key, value in data[0]["body"]["items"][0].items():
    print(key, value)

bizesId 10027626
bizesNm 장모님치킨가창점
brchNm 가창점
indsLclsCd Q
indsLclsNm 음식
indsMclsCd Q05
indsMclsNm 닭/오리요리
indsSclsCd Q05A08
indsSclsNm 후라이드/양념치킨
ksicCd I56193
ksicNm 치킨 전문점
ctprvnCd 27
ctprvnNm 대구광역시
signguCd 27710
signguNm 달성군
adongCd 2771031000
adongNm 가창면
ldongCd 2771031024
ldongNm 가창면
lnoCd 2771031024101200001
plotSctCd 1
plotSctNm 대지
lnoMnno 120
lnoSlno 1
lnoAdr 대구광역시 달성군 가창면 냉천리 120-1
rdnmCd 277103148001
rdnm 대구광역시 달성군 가창면 가창동로
bldMnno 6
bldSlno
bldMngNo 2771031024101200004036858
bldNm
rdnmAdr 대구광역시 달성군 가창면 가창동로 6
oldZipcd 711861
newZipcd 42938
dongNo
flrNo 1
hoNo
lon 128.644458591419
lat 35.7826625402814

In [17]:
result3 = {}
for key, value in data[0]["body"]["items"][0].items():
    result3.setdefault(key, []).append(value)
result3

{'bizesId': ['10027626'],
 'bizesNm': ['장모님치킨가창점'],
 'brchNm': ['가창점'],
 'indsLclsCd': ['Q'],
 'indsLclsNm': ['음식'],
 'indsMclsCd': ['Q05'],
 'indsMclsNm': ['닭/오리요리'],
 'indsSclsCd': ['Q05A08'],
 'indsSclsNm': ['후라이드/양념치킨'],
 'ksicCd': ['I56193'],
 'ksicNm': ['치킨 전문점'],
 'ctprvnCd': ['27'],
 'ctprvnNm': ['대구광역시'],
 'signguCd': ['27710'],
 'signguNm': ['달성군'],
 'adongCd': ['2771031000'],
 'adongNm': ['가창면'],
 'ldongCd': ['2771031024'],
 'ldongNm': ['가창면'],
 'lnoCd': ['2771031024101200001'],
 'plotSctCd': ['1'],
 'plotSctNm': ['대지'],
 'lnoMnno': [120],
 'lnoSlno': [1],
 'lnoAdr': ['대구광역시 달성군 가창면 냉천리 120-1'],
 'rdnmCd': ['277103148001'],
 'rdnm': ['대구광역시 달성군 가창면 가창동로'],
 'bldMnno': [6],
 'bldSlno': [''],
 'bldMngNo': ['2771031024101200004036858'],
 'bldNm': [''],
 'rdnmAdr': ['대구광역시 달성군 가창면 가창동로 6'],
 'oldZipcd': ['711861'],
 'newZipcd': ['42938'],
 'dongNo': [''],
 'flrNo': ['1'],
 'hoNo': [''],
 'lon': [128.644458591419],
 'lat': [35.7826625402814]}

In [18]:
result3 = {}
for shop in data[0]["body"]["items"]:
    for key, value in shop.items():
        result3.setdefault(key, []).append(value)
result3

{'bizesId': ['10027626',
  '10098244',
  '10099459',
  '10136167',
  '10136346',
  '10150151',
  '10186527',
  '10208331',
  '10208355',
  '10208360',
  '10231561',
  '10242205',
  '10274423',
  '10398264',
  '10407416',
  '10423599',
  '10446382',
  '10482089',
  '10623611',
  '10663586',
  '10797221',
  '10843494',
  '10849818',
  '10862582',
  '10863924',
  '10872598',
  '10910446',
  '10915111',
  '10935002',
  '10944198',
  '10944940',
  '10983804',
  '10991930',
  '11040258',
  '11047099',
  '11049106',
  '11061070',
  '11128733',
  '11157227',
  '11232463',
  '11253800',
  '11278610',
  '11287532',
  '11301000',
  '11306589',
  '11376111',
  '11378644',
  '11382583',
  '11427664',
  '11434268',
  '11447247',
  '11448883',
  '11449025',
  '11454601',
  '11458090',
  '11459406',
  '11482381',
  '11483687',
  '11484700',
  '11498882',
  '11507437',
  '11520493',
  '11524244',
  '11524893',
  '11529037',
  '11532764',
  '11541687',
  '11547449',
  '11547684',
  '11552444',
  '11569592',
  '11572236',
  '11576384',
  '11580865',
  '11582307',
  '11589218',
  '11598361',
  '11604910',
  '11619528',
  '11620833',
  '11639762',
  '11695952',
  '11698512',
  '11698975',
  '11699760',
  '11700014',
  '11704659',
  '11705620',
  '11706155',
  '11707011',
  '11709088',
  '11709100',
  '11711027',
  '11711067',
  '11712945',
  '11712956',
  '11714251',
  '11715935',
  '11717248',
  '11717759',
  '11719142',
  '11720675',
  '11721101',
  '11721260',
  '11721518',
  '11722015',
  '11722308',
  '11723189',
  '11723709',
  '11724519',
  '11725002',
  '11727265',
  '11728603',
  '11728649',
  '11728877',
  '11728953',
  '11729200',
  '11729372',
  '11729950',
  '11730479',
  '11730570',
  '11730575',
  '11731974',
  '11732442',
  '11734168',
  '11734343',
  '11735626',
  '11735864',
  '11736539',
  '11740800',
  '11743158',
  '11743386',
  '11744441',
  '11744742',
  '11744874',
  '11746300',
  '11747602',
  '11748021',
  '11748108',
  '11748276',
  '11749496',
  '11749509',
  '11749639',
  '11749776',
  '11749957',
  '11749992',
  '11749998',
  '11750909',
  '11751125',
  '11751132',
  '11751169',
  '11751175',
  '11751178',
  '11751516',
  '11751546',
  '11751704',
  '11751896',
  '11752058',
  '11752062',
  '11752349',
  '11752591',
  '11752630',
  '11752704',
  '11752775',
  '11753013',
  '11753017',
  '11753142',
  '11753154',
  '11753447',
  '11753470',
  '11753656',
  '11753686',
  '11753838',
  '11753865',
  '11753889',
  '11753978',
  '11754154',
  '11754662',
  '11754801',
  '11754906',
  '11755230',
  '11755361',
  '11755471',
  '11755612',
  '11755709',
  '11755923',
  '11756064',
  '11756101',
  '11756181',
  '11756247',
  '11756374',
  '11756535',
  '11756910',
  '11757065',
  '11757118',
  '11757476',
  '11757561',
  '11757584',
  '11757993',
  '11758012',
  '11758203',
  '11758434',
  '11758743',
  '11758765',
  '11758977',
  '11759117',
  '11759582',
  '11759945',
  '11760021',
  '11760153',
  '11760637',
  '11760751',
  '11760915',
  '11760936',
  '11761245',
  '11761446',
  '11761569',
  '11761609',
  '11761830',
  '11761860',
  '11762241',
  '11763246',
  '11763445',
  '11763595',
  '11763660',
  '11763754',
  '11763891',
  '11763956',
  '11764135',
  '11764161',
  '11764347',
  '11764349',
  '11764411',
  '11764492',
  '11764511',
  '11764579',
  '11764656',
  '11764908',
  '11764952',
  '11764987',
  '11765124',
  '11765301',
  '11765586',
  '11765693',
  '11765931',
  '11765945',
  '11766021',
  '11766202',
  '11766233',
  '11766305',
  '11766345',
  '11766652',
  '11766707',
  '11767312',
  '11767415',
  '11767617',
  '11767621',
  '11767659',
  '11767736',
  '11767825',
  '11768010',
  '11768055',
  '11768084',
  '11768773',
  '11768802',
  '11768859',
  '11768871',
  '11768895',
  '11768930',
  '11769147',
  '11769160',
  '11769236',
  '11769340',
  '11769546',
  '11769744',
  '11769941',
  '11770636',
  '11770766',
  '11770918',
  '11771071',
  '11771389',
  '11771511',
  '11771633',
  '11771826',
  '11771917',
  '11771926',
  '11772012',
  '11772251',
  '11772420',
  '11772458',
  '11772806',
  '11773188',
  '11773405',
  '11773451',
  '11773666',
  '11773980',
  '11774159',
  '11774373',
  '11774422',
  '11774515',
  '11774630',
  '11774632',
  '11774737',
  '11774774',
  '11774869',
  '11775003',
  '11775103',
  '11775137',
  '11775204',
  '11775237',
  '11775546',
  '11775816',
  '11775963',
  '11776038',
  '11776170',
  '11776304',
  '11776310',
  '11776578',
  '11776918',
  '11776986',
  '11777268',
  '11777313',
  '11777320',
  '11777367',
  '11777431',
  '11777828',
  '11777857',
  '11777916',
  '11778003',
  '11778191',
  '11778640',
  '11778718',
  '11778941',
  '11778986',
  '11779009',
  '11779035',
  '11779248',
  '11779627',
  '11779636',
  '11780175',
  '11780679',
  '11780715',
  '11780875',
  '11781056',
  '11781288',
  '11781291',
  '11781465',
  '11781528',
  '11781599',
  '11781756',
  '11781905',
  '11781990',
  '11782015',
  '11782102',
  '11782350',
  '11782364',
  '11782438',
  '11782456',
  '11782471',
  '11782536',
  '11782939',
  '11783045',
  '11783139',
  '11783187',
  '11783208',
  '11783433',
  '11783812',
  '11784090',
  '11784166',
  '11784323',
  '11784454',
  '11784463',
  '11784502',
  '11784738',
  '11785408',
  '11785759',
  '11785957',
  '11785973',
  '11786039',
  '11786221',
  '11786535',
  '11786683',
  '11786706',
  '11786721',
  '11787917',
  '11788986',
  '11789197',
  '11789339',
  '11789380',
  '11789622',
  '11789752',
  '11789966',
  '11790146',
  '11790165',
  '11790280',
  '11790359',
  '11790514',
  '11790530',
  '11790549',
  '11790625',
  '11790799',
  '11791077',
  '11791120',
  '11792109',
  '11792259',
  '11792317',
  '11792341',
  '11792716',
  '11793111',
  '11793220',
  '11793265',
  '11793508',
  '11793530',
  '11793701',
  '11794055',
  '11794092',
  '11794100',
  '11794142',
  '11794292',
  '11794307',
  '11794321',
  '11794836',
  '11795028',
  '11795052',
  '11795175',
  '11795300',
  '11795585',
  '11795593',
  '11795617',
  '11795880',
  '11796037',
  '11796332',
  '11796430',
  '11796483',
  '11796529',
  '11796782',
  '11796839',
  '11797068',
  '11797138',
  '11797590',
  '11797607',
  '11797615',
  '11797646',
  '11797663',
  '11797865',
  '11797866',
  '11798688',
  '11799132',
  '11799368',
  '11799369',
  '11799477',
  '11799506',
  '11799526',
  '11799528',
  '11799545',
  '11799607',
  '11799779',
  '11799780',
  '11799805',
  '11800262',
  '11800471',
  '11800657',
  '11800767',
  '11800909',
  '11800936',
  '11801480',
  '11801780',
  '11801792',
  '11801814',
  '11801991',
  '11802594',
  '11803126',
  '11803322',
  '11803339',
  '11803351',
  '11803468',
  '11803518',
  '11803610',
  '11803629',
  '11803736',
  '11803747',
  '11804285',
  '11804607',
  '11804966',
  '11804994',
  '11805083',
  '11805140',
  '11805153',
  '11805160',
  '11805183',
  '11805193',
  '11805194',
  '11805205',
  '11805269',
  '11805274',
  '11805303',
  '11805313',
  '11805314',
  '11805419',
  '11805497',
  '11805745',
  '11806034',
  '11806235',
  '11806609',
  '11806666',
  '11807232',
  '11807344',
  '11807384',
  '11807789',
  '11807794',
  '11807795',
  '11807843',
  '11807874',
  '11807926',
  '11807929',
  '11807933',
  '11807961',
  '11808014',
  '11808022',
  '11808039',
  '11808058',
  '11808063',
  '11808128',
  '11808162',
  '11808240',
  '11808298',
  '11808818',
  '11808839',
  '11809053',
  '11809127',
  '11809147',
  '11809186',
  '11809228',
  '11809264',
  '11809533',
  '11809555',
  '11809964',
  '11810259',
  '11810324',
  '11810336',
  '11810545',
  '11810570',
  '11810844',
  '11811246',
  '11811403',
  '11811430',
  '11811589',
  '11811593',
  '11811641',
  '11811767',
  '11811840',
  '11811853',
  '11811950',
  '11811956',
  '11812162',
  '11812215',
  '11812272',
  '11812474',
  '11812501',
  '11812657',
  '11812920',
  '11813062',
  '11813145',
  '11813166',
  '11813267',
  '11813439',
  '11813493',
  '11813496',
  '11813536',
  '11813788',
  '11813993',
  '11814005',
  '11814008',
  '11814070',
  '11814578',
  '11814702',
  '11814887',
  '11814977',
  '11815033',
  '11815402',
  '11815405',
  '11815435',
  '11815965',
  '11816193',
  '11816494',
  '11816510',
  '11816561',
  '11817371',
  '11817680',
  '11818052',
  '11818241',
  '11818444',
  '11818447',
  '11818587',
  '11818653',
  '11818745',
  '11818783',
  '11818814',
  '11818859',
  '11819142',
  '11819180',
  '11819190',
  '11819264',
  '11819409',
  '11819561',
  '11819562',
  '11822110',
  '11822127',
  '11822318',
  '11822990',
  '11823159',
  '11823234',
  '11823265',
  '11823609',
  '11823838',
  '11823954',
  '11823992',
  '11824020',
  '11824025',
  '11824466',
  '11825027',
  '11825335',
  '11825687',
  '11826029',
  '11826211',
  '11826528',
  '11826596',
  '11826837',
  '11827866',
  '11827951',
  '11828241',
  '11828443',
  '11828535',
  '11829355',
  '11829539',
  '11829946',
  '11830556',
  '11830717',
  '11831043',
  '11831146',
  '11831267',
  '11831621',
  '11831776',
  '11832381',
  '11832608',
  '11833060',
  '11833129',
  '11833192',
  '11833296',
  '11833420',
  '11833690',
  '11833902',
  '11834495',
  '11834789',
  '11835048',
  '11835519',
  '11836702',
  '11838072',
  '11840346',
  '11840759',
  '11840760',
  '11840843',
  '11840854',
  '11840873',
  '11840882',
  '11841432',
  '11841849',
  '11842592',
  '11842704',
  '11843039',
  '11843046',
  '11843499',
  '11843722',
  '11844241',
  '11844251',
  '11845237',
  '11845414',
  '11845481',
  '11845664',
  '11845903',
  '11845997',
  '11846023',
  '11846118',
  '11846121',
  '11846214',
  '11846347',
  '11846585',
  '11848245',
  '11848277',
  '11848611',
  '11848843',
  '11848930',
  '11850416',
  '11850481',
  '11850504',
  '11850615',
  '11850898',
  '11850945',
  '11851011',
  '11851040',
  '11851095',
  '11851175',
  '11851409',
  '11851432',
  '11851767',
  '11852414',
  '11853135',
  '11853152',
  '11853222',
  '11853293',
  '11854101',
  '11854375',
  '11854677',
  '11854685',
  '11856016',
  '11856831',
  '11857241',
  '11858307',
  '11858888',
  '11859019',
  '11860106',
  '11860552',
  '11860719',
  '11861110',
  '11861170',
  '11861503',
  '11863164',
  '11863314',
  '11863328',
  '11863516',
  '11863551',
  '11864249',
  '11865087',
  '11866428',
  '11866491',
  '11866624',
  '11866661',
  '11867065',
  '11867584',
  '11867605',
  '11867863',
  '11868453',
  '11868652',
  '11868655',
  '11869933',
  '11870267',
  '11870353',
  '11870538',
  '11870588',
  '11870857',
  '11870962',
  '11871037',
  '11871257',
  '11871406',
  '11871412',
  '11871514',
  '11871612',
  '11871983',
  '11872382',
  '11872733',
  '11872898',
  '11873348',
  '11873939',
  '11874353',
  '11874397',
  '11874404',
  '11874413',
  '11874523',
  '11874539',
  '11874579',
  '11874982',
  '11876188',
  '11876478',
  '11876844',
  '11876872',
  '11876947',
  '11877776',
  '11877874',
  '11877892',
  '11878050',
  '11878064',
  '11878577',
  '11879570',
  '11879751',
  '11880196',
  '11880666',
  '11880842',
  '11881229',
  '11881532',
  '11881734',
  '11882065',
  '11882074',
  '11882567',
  '11883018',
  '11883886',
  '11884289',
  '11885203',
  '11885412',
  '11886028',
  '11886943',
  '11887111',
  '11887199',
  '11887253',
  '11887868',
  '11888709',
  '11888770',
  '11890404',
  '11890714',
  '11891472',
  '11891647',
  '11891666',
  '11891711',
  '11892316',
  '11892370',
  '11894135',
  '11895526',
  '11896208',
  '11896276',
  '11896523',
  '11896934',
  '11896965',
  '11896984',
  '11897325',
  '11897555',
  '11897913',
  '11898931',
  '11899546',
  '11899548',
  '11899887',
  '11900066',
  '11900117',
  '11900258',
  '11900975',
  '11901113',
  '11901734',
  '11902136',
  '11902259',
  '11902795',
  '11903657',
  '11905097',
  '11905223',
  '11906306',
  '11906380',
  '11906381',
  '11906464',
  '11906603',
  '11906860',
  '11906928',
  '11907110',
  '11907608',
  '11907683',
  '11907742',
  '11907762',
  '11907874',
  '11908210',
  '11908250',
  '11908591',
  '11908999',
  '11909442',
  '11909516',
  '11909545',
  '11909698',
  '11909860',
  '11910006',
  '11910109',
  '11910157',
  '11910245',
  '11910320',
  '11910354',
  '11910630',
  '11910760',
  '11910970',
  '11910978',
  '11911273',
  '11911569',
  '11911656',
  '11911688',
  '11911933',
  '11911993',
  '11912081',
  '11912091',
  '11912507',
  '11912537',
  '11912560',
  '11912682',
  '11912785',
  '11912791',
  '11912812',
  '11912881',
  '11912926',
  '11913023',
  '11913126',
  '11913222',
  '11913415',
  '11913468',
  '11913636',
  '11913812',
  '11913822',
  '11914027',
  '11914070',
  '11914185',
  '11914284',
  '11914465',
  '11914554',
  '11914571',
  '11914663',
  '11914674',
  '11914831',
  '11915034',
  '11915685',
  '11915718',
  '11915828',
  '11916020',
  '11916112',
  '11916494',
  '11916649',
  '11916883',
  '11917139',
  '11917265',
  '11917439',
  '11917445',
  '11917558',
  '11917594',
  '11917595',
  '11917628',
  '11917853',
  '11918003',
  '11918011',
  '11918398',
  '11918958',
  '11918986',
  '11920586',
  '11921047',
  '11921077',
  '11921155',
  '11921159',
  '11921192',
  '11921193',
  '11921290',
  '11921361',
  '11921546',
  '11921597',
  '11921634',
  '11921668',
  '11921741',
  '11921760',
  '11921763',
  '11921871',
  '11922065',
  '11922205',
  '11922289',
  '11922306',
  '11922419',
  '11922471',
  '11922489',
  '11922537',
  '11922549',
  '11922695',
  '11922735',
  '11922770',
  '11923039',
  '11923217',
  '11923310',
  '11923401',
  '11923462',
  '11923482',
  '11923624',
  '11923750',
  '11923801',
  '11923803',
  '11923986',
  '11923990',
  '11924061',
  '11924548',
  '11924586',
  '11925051',
  '11925219',
  '11925311',
  '11925356',
  '11925435',
  '11925443',
  '11925454',
  '11925524',
  '11925703',
  '11925718',
  '11925865',
  '11925984',
  '11926088',
  '11926418',
  '11926426',
  '11926466',
  '11926562',
  '11926566',
  '11926896',
  '11926925',
  '11927120',
  '11927310',
  '11927491',
  '11927616',
  '11927757'],
 'bizesNm': ['장모님치킨가창점',
  '짱구피자치킨',
  '쭈노치킨',
  '치킨뱅이',
  '치킨월드율량점',
  'KFC',
  '토마토두마리치킨',
  '페리카나치킨연수우성체인점',
  '페리카나치킨벽산분점',
  '페리카나치킨',
  '피자앤닭컴',
  '하림치킨',
  '핫썬치킨옥동점',
  'BHC치킨',
  '치킨아이',
  '더화덕',
  '월드양념통닭',
  'BBQ치킨',
  '치킨마루',
  '교촌치킨',
  '새때치킨대산점',
  '본스치킨',
  '치킨매니아',
  '둘둘치킨',
  '굽네치킨',
  'BHC치킨',
  '교촌',
  '맛있는파닭',
  '보드람치킨',
  '오븐에꾸운닭',
  'BBQ치킨완주3공단점',
  '자담치킨앤호프카페',
  '교촌치킨',
  '페리카나중곡2점',
  '땡큐맘치킨',
  '이맛치킨',
  '쥬라기치킨',
  '네네치킨',
  '티바두마리치킨',
  '교촌치킨',
  '지코바양념치킨',
  '페리카나치킨',
  '자연담은치킨',
  '굽네치킨',
  '교촌치킨',
  '교촌치킨',
  'BBQ치킨',
  '노랑통닭',
  '꿀닭',
  '에디슨DHA치킨',
  'BBQ치킨',
  '꿀닭',
  '페리카나치킨삼척당저점',
  '다져스치킨',
  '오븐에꾸운닭',
  '동키치킨',
  'BHC치킨',
  '네네치킨',
  '네네치킨',
  '또래오래',
  '에디슨DHA치킨하안점',
  '통티닭강정',
  '멕시칸치킨',
  '처갓집양념치킨',
  'BBQ치킨',
  '구어스치킨',
  '꿀닭화명점',
  '깐부치킨',
  '코리안숯불바베큐',
  '부어치킨만수6동점',
  '페리카나치킨',
  '교촌치킨',
  '달콤한닭강정',
  'BHC치킨',
  '에디슨DHA치킨',
  '교촌치킨중계역점',
  '페리카나',
  '닭사부',
  '네네치킨상암점',
  'KFC서초우성점',
  '다기야',
  '도깨비치킨',
  '부어치킨작전서운동점',
  '멕시카나동삼점',
  'BHC치킨익산동산점',
  'BBQ치킨상모사곡점',
  '멕시칸치킨동부보성점',
  '지코바숯불양념치킨충주1호점',
  '쓰리피치킨',
  'BHC치킨정읍수성점',
  '페리카나',
  '치킨매니아부산화명점',
  'BHC치킨광주일곡점',
  '호식이두마리치킨화정점',
  '멕시칸치킨창신점',
  '에디슨DHA치킨남산타운점',
  '에디슨DHA치킨용인신갈지구점',
  '에디슨DHA치킨',
  '멕시카나비산점',
  '에디슨DHA치킨양주자이점',
  '강정이가기가막혀율량사천점',
  '맘스터치목동2호점',
  '페리카나삼천점',
  '멕시카나토평점',
  '치킨신드롬쌍문1호',
  '처갓집양념치킨',
  '페리카나평촌2점',
  '속초닭강정',
  '아프리카치킨',
  '큰통치킨',
  'BBQ치킨',
  '구어조은닭가경점',
  '페리카나청주영동점',
  'BBQ치킨용인상현점',
  'BHC치킨오산원동점',
  '맘스터치화명점',
  '치킨678전주아중점',
  '맥켄치킨',
  '쪼끼군다리치킨',
  '부어치킨영광읍점',
  '멜롱닭',
  '치킨매니아산본2호점',
  '라이스팡조치원점',
  '치킨매니아정릉1호점',
  '멕시카나',
  '굽자나조치원점',
  '페리카나신원당점',
  'BBQ치킨화정달빛마을점',
  'BHC치킨신포점',
  '치킨678대전가오점',
  '부어치킨도담마을점',
  '가보세통닭',
  '네네치킨삼학점',
  '지코바숯불양념치킨',
  '감사합니닭',
  'BBQ치킨',
  'BBQ치킨',
  '교촌치킨',
  'BBQ치킨김해외동점',
  '컬투치킨덕소사랑1호점',
  '티바두마리치킨',
  '가마로강정',
  '클레어수제치킨',
  '옛날통닭노형점',
  '조선통닭',
  '마일드치킨',
  'BHC치킨',
  '돈치킨',
  '놀부옛날통닭퇴계1호점',
  '치킨반장',
  '비에이치시',
  'BBQ치킨',
  'BBQ치킨',
  '바른치킨',
  '호야옛날통닭',
  '꼬꼬집합소',
  'BHC치킨',
  '6일닭강정',
  '피자샵해남점',
  '학성통닭',
  '경아두마리치킨',
  '디디치킨석동점',
  '옛날통닭',
  '옛날가마솥시골통닭',
  '맥켄치킨',
  '교촌치킨',
  '소문난통닭5900',
  '또봉이통닭',
  '교촌치킨곤지암점',
  '조선의옛날통닭',
  '치코파닭',
  '놀부옛날통닭용암점',
  '서가마통닭',
  '1988추억의통닭',
  '호식이두마리치킨',
  '네네치킨',
  '멕시카나치킨',
  'BBQ치킨',
  '먹방',
  '교촌치킨',
  '화계치킨',
  '바른치킨',
  '네네치킨',
  '충만치킨오류점',
  '용천옛날통닭',
  '송원닭집',
  '신화치킨',
  '네네치킨',
  'BHC치킨',
  '옛날통닭',
  '고담치킨',
  '미소치킨',
  '써니치킨',
  '치킨퐁백운점',
  '네네치킨',
  '옛날통닭',
  '옛날통닭지귀점',
  '부어치킨노암점',
  '홍치킨',
  '태진티앤디',
  '치킨더비',
  '믹스밥',
  '북일치킨',
  '호식이두마리치킨신시가지점',
  'BHC치킨',
  'KFC',
  '옛날통닭',
  '두리통닭',
  '용안통닭',
  '허선생치킨',
  '지코바양념치킨송도점',
  '다겐닭스',
  '바르닭치킨',
  '가마솥치킨',
  '유나네후다닭통닭',
  '8800켄터키치킨',
  '놀부옛날통닭',
  'BHC치킨',
  '호치킨하우스',
  '깐부치킨',
  '티바두마리치킨',
  '처가집',
  'BHC치킨',
  '또봉이통닭',
  '호식이두마리치킨',
  '호식이두마리치킨',
  '명품통닭',
  '멕시카나',
  '디디치킨',
  '충만치킨',
  '박군치킨',
  '장모님옛날통닭',
  '딸부자네통닭',
  '꽃보다치킨',
  '호치킨',
  '노랑통닭',
  '교촌치킨풍호점',
  'BHC치킨',
  'BHC치킨',
  '미쳐버린파닭',
  '통닭원5900',
  'BHC치킨우석대점',
  '처갓집양념치킨',
  '한국통닭',
  '옛날통닭',
  '파닭파닭',
  '옛날통닭여상점',
  '추억의옛날통닭',
  '시골통닭',
  '네네치킨합천점',
  '윤가네옛날통닭',
  '옛날통닭새벽닭',
  '옛날통닭',
  '위키드스노우썬더치킨',
  'BBQ치킨',
  '신통치킨',
  '영달이두마리치킨',
  '오븐愛통닭',
  '교촌치킨',
  'BBQ치킨',
  'BHC치킨중산사월점',
  '필바든치킨소사벌점',
  '산동요리점',
  '구통치킨칠곡읍내점',
  '치킨처럼',
  '또닭또닭',
  '큐스',
  '더썬치킨남',
  'BBQ치킨',
  '디디치킨',
  '노랑통닭',
  '한국통닭',
  '옛날통닭',
  'BHC치킨',
  '그집마늘치킨신평점',
  '가마로강정정림점',
  '지코바양념치킨',
  '치킨퐁',
  '치킨아지트',
  '짱치킨',
  'BHC치킨도봉점',
  '신나계옛날통닭',
  'BBQ치킨',
  '고기굽는남자',
  '경성옛날통닭',
  '치킨통',
  '달구치킨',
  'Bhc치킨',
  '바른치킨여주대점',
  '못말리는파닭',
  '땅땅치킨',
  '투존치킨',
  '네네치킨함열점',
  '처갓집양념치킨',
  '꼴통닭선생',
  'BHC치킨',
  '본스치킨',
  '중앙통닭',
  '그시절옛날통닭',
  '동래통닭',
  '노랑통닭',
  '태양치킨',
  '치킨매니아',
  '멕시카나치킨',
  '신통치킨',
  'BHC치킨불국점',
  'BBQ치킨',
  '홀릭옛날통닭',
  '진미통닭',
  '명품통닭',
  '또봉이통닭',
  '국빈치킨',
  '네네치킨',
  '대구통닭',
  '60계치킨',
  '유강옛날통닭',
  '황제두마리치킨',
  'TG원닭강정',
  '우리동네닭집탕정',
  '삼대가옛날통닭',
  '티바두마리치킨',
  '천년지기',
  '노랑통닭',
  '가마로강정',
  '가마로강정',
  '박군치킨',
  '허갈닭강정',
  '옛날시골통닭',
  '노랑통닭',
  '교촌치킨',
  '투마리치킨',
  '구통치킨',
  '치킨아이',
  '옛날통닭',
  '신통치킨',
  'BHC치킨',
  '정원치킨',
  '이서방양념치킨',
  '신둔페리카나',
  '좋은통닭',
  '람스두마리치킨',
  '승리의통닭',
  '호로록통닭',
  '울랄라바베큐',
  '깻잎두마리치킨남악점',
  '왕천파닭',
  '황당한치킨용이점',
  '부라더짬뽕치킨',
  '돈치킨',
  '호식이두마리치킨',
  '시장통닭',
  '한앤둘치킨',
  'BHC치킨',
  '상문이숯불두마리치킨신안평거점',
  '또래오래삼성점',
  '명품옛날시골통닭',
  '쌀통닭',
  '또봉이통닭오산운암점',
  '꿈애본통닭',
  '치킨더홈',
  '켄지',
  'BBQ치킨',
  'BHC치킨',
  'TeaCup',
  '옛날통닭',
  '가마솥옛날통닭',
  '치킨마루',
  '든든치킨',
  '공룡치킨',
  '투존치킨교암점',
  '시장통닭',
  '처갓집양념치킨.명가치킨',
  'BBQ치킨제주봉개점',
  '호식이두마리치킨',
  'BHC치킨',
  '치킨처럼',
  'BHC치킨',
  '왕대벌치킨',
  '다모아식당치킨호프',
  '옛날통닭',
  '동큐치킨',
  '쌍파닭',
  '와우치킨',
  '꿈에본닭',
  '둘리치킨',
  '멕시칸치킨',
  '씨앤에프후라이드치킨',
  '멕시칸치킨',
  '맥스양념치킨',
  '맥시칸양념통닭',
  '맥시칸양념통닭',
  '헬로순살치킨',
  '리스치킨',
  '멕시칸치킨',
  '예스굿치킨',
  '멕시칸치킨',
  '놀부살로만치킨',
  '샤르망치킨호프',
  '돈치킨',
  '꼬꼬네치킨호프',
  '에그파파치킨박달점',
  '교촌치킨',
  '알라디아치킨',
  '페리카나홍제점',
  '깨돌치킨',
  'BHC치킨원앙행복점',
  '조광심민속왕순대',
  '신날개',
  '오븐에빠진닭',
  '토토안동선계찜닭',
  '누룽지통닭구이',
  '공항치킨',
  '티바두마리치킨옥정점',
  '진미가마솥통닭',
  '페리카나혁신도시점',
  '마장동육회포차앤문어흑형치킨',
  '불로불러정남점',
  'BBQ치킨광주화정점',
  '훌랄라참숯바베큐치킨곤지암리조트점',
  '본투비마늘치킨종로5가점',
  '고대삼성삼통치킨',
  '통큐치킨',
  'BHC치킨오천고천점',
  '팜치킨호프',
  '김가네얼큰이',
  '목포시장닭집',
  '바니치킨호프',
  '발리두번째이야기',
  '캠프치킨',
  '지코바양념치킨',
  '네네치킨서귀포2호점',
  '치킨신드롬',
  '두존두마리치킨',
  '멕시카나순성점',
  '디디치킨',
  '호식이두마리치킨읍내점',
  'BBQ치킨아침고요수목원점',
  '장모님치킨삼랑진점',
  '계림원누룽지통닭구이부평점',
  '페리카나',
  '피자나라치킨공주부천약대점',
  '야들리애치킨',
  '삼삼S치킨',
  '허갈닭강정용운점',
  '쌀통닭금호1호점',
  '거성치킨',
  '얼큰이통닭',
  '닭집',
  '매운찜닭',
  '페리카나',
  '바투치킨',
  '멕시칸치킨',
  '아쁘리까',
  '신하양념치킨',
  '교촌치킨',
  'BBQ치킨',
  '굿타임페리카나',
  '코리엔탈깻잎치킨',
  '페리카나',
  '굿모닝피자치킨',
  '교촌치킨',
  '처갓집양념치킨안정점',
  '멕시칸치킨',
  '두존두마리치킨문덕오천점',
  '장모님치킨',
  '또래오래',
  '지코바숯불치킨장평점',
  '훌랄라참숯바베큐치킨송담점',
  '멕시칸치킨',
  '옛날통닭',
  '킴스바베큐',
  '쌀개통닭',
  '연동치킨호프',
  '더착한79치킨충남대점',
  '만남치킨&호프',
  '삼오통닭호프',
  '양키즈',
  '대구통닭',
  '맘스터치안지랑역점',
  '페리카나강구점',
  '피자나라치킨공주',
  '시골통닭',
  '36계누룽지통닭구이',
  '동키치킨',
  '달리는꼬꼬숯불치킨',
  '노랑통닭',
  '굽네치킨난지캠핑장점난지캠핑장점',
  '굽네치킨',
  '굽네치킨율하점',
  '굽네치킨여수관문점',
  '굽네치킨내수점',
  '굽네치킨광주하나로클럽점',
  '멕시카나치킨진영점',

In [19]:
result3 = {}
for page in data:
    for shop in page["body"]["items"]:
        for key, value in shop.items():
            result3.setdefault(key, []).append(value)
df3 = pd.DataFrame(result3)
df3

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36059,9829515,아리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010200106740003008662,,경기도 동두천시 거북마루로 6,483020,11348,,1,,127.046713,37.895702
36060,9851302,애니치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4785031036104090002008916,,경상북도 칠곡군 지천면 신동로 147,718821,39864,,,,128.488717,35.956631
36061,9867543,에디슨치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1135010600103590001010681,중계5단지주공아파트,서울특별시 노원구 중계로 230,139781,01713,,1,,127.075031,37.651004
36062,9918905,오븐에꾸운닭장유점,장유점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4825031027103150002091993,재영프라자,경상남도 김해시 삼문로 26,621280,51004,,1,,128.803565,35.192491
36063,9967953,웰빙치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011100101360002016167,,강원도 원주시 상지대길 43,220954,26342,,1,,127.937290,37.369591

In [20]:
print(len(data[0]["header"]["columns"]))
data[0]["header"]["columns"]
len(data[0]["body"]["items"][0].keys())

39

39

In [21]:
result3 = {}
for page in data:
    for shop in page["body"]["items"]:
        for key, value in zip(data[0]["header"]["columns"], shop.values()):
            result3.setdefault(key, []).append(value)
df3 = pd.DataFrame(result3)
df3

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36059,9829515,아리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010200106740003008662,,경기도 동두천시 거북마루로 6,483020,11348,,1,,127.046713,37.895702
36060,9851302,애니치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4785031036104090002008916,,경상북도 칠곡군 지천면 신동로 147,718821,39864,,,,128.488717,35.956631
36061,9867543,에디슨치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1135010600103590001010681,중계5단지주공아파트,서울특별시 노원구 중계로 230,139781,01713,,1,,127.075031,37.651004
36062,9918905,오븐에꾸운닭장유점,장유점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4825031027103150002091993,재영프라자,경상남도 김해시 삼문로 26,621280,51004,,1,,128.803565,35.192491
36063,9967953,웰빙치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011100101360002016167,,강원도 원주시 상지대길 43,220954,26342,,1,,127.937290,37.369591

In [23]:
df3.to_csv("./data/전국_치킨집_리스트.csv", index = False, encoding = "utf-8-sig")